// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5sDD_VUQVuaPgs8cfL8cswCk5m7KKRg',
    appId: '1:577975338466:web:f2b9d603a38a56e957a5bb',
    messagingSenderId: '577975338466',
    projectId: 'flutterfiredb01',
    authDomain: 'flutterfiredb01.firebaseapp.com',
    storageBucket: 'flutterfiredb01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihkuCxlqBBGwsQQV6DM9Te9MBdiQLCH0',
    appId: '1:577975338466:android:14e836f88cd65ad257a5bb',
    messagingSenderId: '577975338466',
    projectId: 'flutterfiredb01',
    storageBucket: 'flutterfiredb01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88Cw2KNuxEmxVGhM9IPwgzucXnxC9mHo',
    appId: '1:577975338466:ios:5aeac27a8113f10e57a5bb',
    messagingSenderId: '577975338466',
    projectId: 'flutterfiredb01',
    storageBucket: 'flutterfiredb01.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88Cw2KNuxEmxVGhM9IPwgzucXnxC9mHo',
    appId: '1:577975338466:ios:5aeac27a8113f10e57a5bb',
    messagingSenderId: '577975338466',
    projectId: 'flutterfiredb01',
    storageBucket: 'flutterfiredb01.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk5sDD_VUQVuaPgs8cfL8cswCk5m7KKRg',
    appId: '1:577975338466:web:8ced2be228316f6c57a5bb',
    messagingSenderId: '577975338466',
    projectId: 'flutterfiredb01',
    authDomain: 'flutterfiredb01.firebaseapp.com',
    storageBucket: 'flutterfiredb01.appspot.com',
  );
}
