name: notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  image_picker: ^1.0.8
  path: ^1.8.3
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.6.1
  flutter_config: ^2.0.2
  hexcolor: ^3.0.1
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  http: ^1.2.1
  path_provider: ^2.1.3
  cross_file: ^0.3.4+1
  image_picker_for_web: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
